spring.application.name=country_currency_exchange_rate

spring.datasource.url=jdbc:mysql://localhost:3306/country_currency_exchange_rate
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

COUNTRY_DATA_URL=https://restcountries.com/v2/all?fields=name,capital,region,population,flag,currencies
EXCHANGE_RATE_URL=https://open.er-api.com/v6/latest/USD
